// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductService.Infrastructure.Data;

#nullable disable

namespace ProductService.Infrastructure.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20251118102232_UpdateTableBrand")]
    partial class UpdateTableBrand
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductService.Domain.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BrandCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BrandDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BrandCode = "LOGI",
                            BrandDescription = "High quality peripherals and accessories",
                            BrandImage = "logitech.png",
                            BrandName = "Logitech",
                            DateCreated = new DateTime(2025, 11, 18, 10, 22, 31, 651, DateTimeKind.Utc).AddTicks(8417),
                            DateModified = new DateTime(2025, 11, 18, 10, 22, 31, 651, DateTimeKind.Utc).AddTicks(8647),
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-222222222222"),
                            BrandCode = "KEYC",
                            BrandDescription = "Premium customizable mechanical keyboards",
                            BrandImage = "keychron.png",
                            BrandName = "Keychron",
                            DateCreated = new DateTime(2025, 11, 18, 10, 22, 31, 651, DateTimeKind.Utc).AddTicks(9161),
                            DateModified = new DateTime(2025, 11, 18, 10, 22, 31, 651, DateTimeKind.Utc).AddTicks(9162),
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("ProductService.Domain.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            ImageName = "mx_mechanical.png",
                            ImagePath = "/images/products/mx_mechanical.png",
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            ImageName = "k8_pro.png",
                            ImagePath = "/images/products/k8_pro.png",
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = new Guid("22222222-2222-2222-2222-333333333333")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            ImageName = "g502x.png",
                            ImagePath = "/images/products/g502x.png",
                            IsActive = true,
                            IsDeleted = false,
                            ProductId = new Guid("22222222-2222-2222-2222-444444444444")
                        });
                });

            modelBuilder.Entity("ProductService.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AttributesJson = "{\"Color\":\"Gray\",\"Switch\":\"Tactile Quiet\",\"Layout\":\"US\"}",
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryId = "",
                            Created = new DateTime(2025, 11, 18, 10, 22, 31, 653, DateTimeKind.Utc).AddTicks(7596),
                            IsActive = true,
                            IsDeleted = false,
                            Modified = new DateTime(2025, 11, 18, 10, 22, 31, 653, DateTimeKind.Utc).AddTicks(7793),
                            Price = 836.12,
                            ProductDescription = "Low-profile mechanical keyboard with quiet tactile switches.",
                            ProductName = "Logitech MX Mechanical Keyboard",
                            Sku = "LOGI-MX-KEY",
                            Stock = 100,
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-333333333333"),
                            AttributesJson = "{\"Color\":\"Black\",\"Switch\":\"Gateron Brown\",\"Connectivity\":\"Bluetooth 5.1\"}",
                            BrandId = new Guid("11111111-1111-1111-1111-222222222222"),
                            CategoryId = "",
                            Created = new DateTime(2025, 11, 18, 10, 22, 31, 653, DateTimeKind.Utc).AddTicks(8308),
                            IsActive = true,
                            IsDeleted = false,
                            Modified = new DateTime(2025, 11, 18, 10, 22, 31, 653, DateTimeKind.Utc).AddTicks(8308),
                            Price = 0.0,
                            ProductDescription = "Hot-swappable wireless mechanical keyboard with RGB backlight.",
                            ProductName = "Keychron K8 Pro",
                            Sku = "KEYC-K8PRO",
                            Stock = 50,
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-444444444444"),
                            AttributesJson = "{\"Color\":\"White\",\"DPI\":\"25600\",\"Buttons\":\"13\"}",
                            BrandId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CategoryId = "",
                            Created = new DateTime(2025, 11, 18, 10, 22, 31, 653, DateTimeKind.Utc).AddTicks(8311),
                            IsActive = true,
                            IsDeleted = false,
                            Modified = new DateTime(2025, 11, 18, 10, 22, 31, 653, DateTimeKind.Utc).AddTicks(8311),
                            Price = 0.0,
                            ProductDescription = "Wireless gaming mouse with LIGHTSPEED and LIGHTSYNC RGB.",
                            ProductName = "Logitech G502 X Plus Mouse",
                            Sku = "LOGI-G502X",
                            Stock = 200,
                            UserId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-dddddddddddd")
                        });
                });

            modelBuilder.Entity("ProductService.Domain.Entities.Image", b =>
                {
                    b.HasOne("ProductService.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ProductService.Domain.Entities.Product", b =>
                {
                    b.HasOne("ProductService.Domain.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("ProductService.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ProductService.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
