// <auto-generated />
using System;
using CategoryService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CategoryService.Infrastructure.Migrations
{
    [DbContext(typeof(CategoryDbContext))]
    partial class CategoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategoryService.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CategoryName = "Chipset",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(6821),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CategoryName = "Intel",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7264),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CategoryName = "Intel 9",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7271),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CategoryName = "Intel 7",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7275),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CategoryName = "Intel 5",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7278),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CategoryName = "Intel 3",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7284),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000009")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CategoryName = "AMD",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7286),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CategoryName = "AMD R3",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7289),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CategoryName = "AMD R5",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7378),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CategoryName = "AMD R7",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7382),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CategoryName = "AMD R9",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7387),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000010")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CategoryName = "Video Graphic Array (VGA)",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7391),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CategoryName = "NVIDIA",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7394),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CategoryName = "RTX 4000 Series",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7396),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000019")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CategoryName = "RTX 3000 Series",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7400),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000019")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CategoryName = "GTX 1000 Series",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7403),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000019")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CategoryName = "AMD",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7405),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CategoryName = "Radeon RX 7000",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7408),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000023")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CategoryName = "Radeon RX 6000",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7411),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000023")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CategoryName = "Radeon RX 5000",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7414),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000023")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            CategoryName = "Brands",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7418),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            CategoryName = "ASUS",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7421),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000027")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            CategoryName = "MSI",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7423),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000027")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            CategoryName = "Gigabyte",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7427),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000027")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            CategoryName = "EVGA",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7430),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000027")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CategoryName = "Motherboard",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7432),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            CategoryName = "Intel Platform",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7474),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            CategoryName = "Z790",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7476),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000032")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            CategoryName = "B760",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7479),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000032")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            CategoryName = "H710",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7481),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000032")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            CategoryName = "AMD Platform",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7483),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            CategoryName = "X670",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7486),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000036")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            CategoryName = "B650",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7489),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000036")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            CategoryName = "A520",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7492),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000036")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            CategoryName = "Form Factor",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7494),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            CategoryName = "ATX",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7497),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000040")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            CategoryName = "Micro-ATX",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7500),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000040")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            CategoryName = "Mini-ITX",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7502),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000040")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CategoryName = "Storage",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7505),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            CategoryName = "SSD",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7508),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            CategoryName = "NVMe M.2",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7510),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000044")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            CategoryName = "SATA 2.5\"",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7513),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000044")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            CategoryName = "PCIe 4.0",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7515),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000044")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            CategoryName = "HDD",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7548),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            CategoryName = "3.5\" Desktop",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7551),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000048")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            CategoryName = "2.5\" Laptop",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7553),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000048")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000051"),
                            CategoryName = "Enterprise",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7555),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000048")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000052"),
                            CategoryName = "Brands",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7557),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000053"),
                            CategoryName = "Samsung",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7560),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000052")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000054"),
                            CategoryName = "Western Digital",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7562),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000052")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000055"),
                            CategoryName = "Seagate",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7565),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000052")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000056"),
                            CategoryName = "Crucial",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7567),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000052")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CategoryName = "Power Supply Unit (PSU)",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7569),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000057"),
                            CategoryName = "Wattage",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7572),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000058"),
                            CategoryName = "500W-650W",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7574),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000057")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000059"),
                            CategoryName = "700W-850W",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7576),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000057")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000060"),
                            CategoryName = "1000W+",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7579),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000057")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000061"),
                            CategoryName = "Efficiency",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7582),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000062"),
                            CategoryName = "80+ Gold",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7584),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000061")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000063"),
                            CategoryName = "80+ Platinum",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7586),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000061")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000064"),
                            CategoryName = "80+ Titanium",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7589),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000061")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000065"),
                            CategoryName = "Brands",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7621),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000066"),
                            CategoryName = "Corsair",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7623),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000065")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000067"),
                            CategoryName = "EVGA",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7625),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000065")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000068"),
                            CategoryName = "Seasonic",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7628),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000065")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000069"),
                            CategoryName = "be quiet!",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7631),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000065")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CategoryName = "Cooling Fan, Case",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7633),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000070"),
                            CategoryName = "CPU Cooling",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7635),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000071"),
                            CategoryName = "Air Coolers",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7637),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000070")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000072"),
                            CategoryName = "AIO Liquid Coolers",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7640),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000070")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000073"),
                            CategoryName = "Custom Loops",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7642),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000070")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000074"),
                            CategoryName = "Case Fans",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7644),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000075"),
                            CategoryName = "120mm",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7647),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000074")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000076"),
                            CategoryName = "140mm",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7650),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000074")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000077"),
                            CategoryName = "RGB Fans",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7652),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000074")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000078"),
                            CategoryName = "PC Cases",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7655),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000079"),
                            CategoryName = "Full Tower",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7687),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000078")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000080"),
                            CategoryName = "Mid Tower",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7690),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000078")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000081"),
                            CategoryName = "Mini ITX",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7692),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000078")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CategoryName = "KitPraid's PC",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7694),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000082"),
                            CategoryName = "Gaming PC",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7696),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000083"),
                            CategoryName = "Entry Level",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7698),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000082")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000084"),
                            CategoryName = "Mid Range",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7701),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000082")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000085"),
                            CategoryName = "High End",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7703),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000082")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000086"),
                            CategoryName = "Workstation PC",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7705),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000087"),
                            CategoryName = "Content Creation",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7708),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000086")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000088"),
                            CategoryName = "CAD/3D Modeling",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7710),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000086")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000089"),
                            CategoryName = "Video Editing",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7713),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000086")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000090"),
                            CategoryName = "Office PC",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7715),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000091"),
                            CategoryName = "Budget",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7717),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000090")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000092"),
                            CategoryName = "Standard",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7720),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000090")
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000093"),
                            CategoryName = "Premium",
                            Created = new DateTime(2025, 11, 26, 7, 16, 33, 723, DateTimeKind.Utc).AddTicks(7722),
                            IsActive = true,
                            Modified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ParentCategoryId = new Guid("00000000-0000-0000-0000-000000000090")
                        });
                });

            modelBuilder.Entity("CategoryService.Domain.Entities.Category", b =>
                {
                    b.HasOne("CategoryService.Domain.Entities.Category", "ParentCategory")
                        .WithMany("ChildCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("CategoryService.Domain.Entities.Category", b =>
                {
                    b.Navigation("ChildCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
